services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    network_mode: host
    depends_on:
      - caddy
    environment:
      - DOMAIN=$DOMAIN
      - TURN_SECRET=$TURN_SECRET
      - COTURN_REALM=$COTURN_REALM
      - COTURN_EXTERNAL_IP=$COTURN_EXTERNAL_IP
      - COTURN_MIN_PORT=$COTURN_MIN_PORT
      - COTURN_MAX_PORT=$COTURN_MAX_PORT
    volumes:
      - caddy_data:/caddy_data:ro
    restart: unless-stopped
    command:
      - turnserver
      - -n
      - -a
      - -v
      - --fingerprint
      - --no-multicast-peers
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET}
      - --realm=${COTURN_REALM}
      - --external-ip=${COTURN_EXTERNAL_IP}
      - --listening-port=3478
      - --listening-ip=0.0.0.0
      - --min-port=${COTURN_MIN_PORT}
      - --max-port=${COTURN_MAX_PORT}

  signaling-server:
    image: ghcr.io/htl-leo-club-embedded-iot/Stargate-Backend/browser-webrtc:latest
    container_name: signaling-server
    environment:
      - PORT=$SIGNALING_PORT
      - TURN_URL=$TURN_URL
      - TURN_SECRET=$TURN_SECRET
      - AUTH_PIN=$AUTH_PIN
      - AUTH_MASTER_KEY=$AUTH_MASTER_KEY
      - AUTH_TOKEN_EXPIRY_DAYS=$AUTH_TOKEN_EXPIRY_DAYS
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
